
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-worker
  namespace: development
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: storage-worker
  template:
    metadata:
      labels:
        app: storage-worker
    spec:
      nodeSelector:
        dedicated: deamond
      containers:
        - name: storage-worker
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: redis-host
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: redis-password
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: kafka-host
            - name: LOGSTASH_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: logstash-host
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mongo-host
            - name: MONGODB_USER
              value: root
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongodb-root-password
          livenessProbe:
            exec:
              command:
                - cat
                - /app/healthy.txt
            initialDelaySeconds: 60
            periodSeconds: 5
          args:
            - rm -rf /app/aws-iam-authenticator
            - rm -rf /app/kubectl
            - rm -rf /app/Dockerfile