package mongodb

var AdvEventDataModel = "ClientDatabase.adv_events"
var BuyingEventModel = "ClientDatabase.buying_events"
var ChurnBlockerMlResultModel = "ClientDatabase.churn_bloker_ml_results"
var ChurnPredictionMlResultModel = "ClientDatabase.churn_prediction_ml_result_models"
var ClientDataModel = "ClientDatabase.client_data_models"
var EnemyBaseLevelFailModel = "ClientDatabase.enemy_base_level_fail_models"
var EnemyBaseLoginLevelModel = "ClientDatabase.enemy_base_login_level_models"
var GameSessionModel = "ClientDatabase.game_session_models"
var HardwareModel = "ClientDatabase.hardware_models"
var LevelBaseSessionModel = "ClientDatabase.level_base_session_models"
var LocationModel = "ClientDatabase.location_models"
var ManuelFlowModel = "ClientDatabase.manuel_flow_models"
var OfferBehaviorModel = "ClientDatabase.offer_behavior_models"
var ScreenClickModel = "ClientDatabase.screen_click_models"
var ScreenSwipeModel = "ClientDatabase.screen_swipe_models"
var InventoryModel = "ClientDatabase.inventory_models"
var ItemModel = "ClientDatabase.item_models"
var SkillModel = "ClientDatabase.skill_models"
var TemporaryAbilityModel = "ClientDatabase.temporary_ability_model"
