package cassandra

var AdvEventDataModel = "adv_events"
var BuyingEventModel = "buying_events"
var ChurnBlockerMlResultModel = "churn_bloker_ml_results"
var ChurnPredictionMlResultModel = "churn_prediction_ml_results"
var ClientDataModel = "clients"
var EnemyBaseLevelFailModel = "enemy_base_level_fails"
var EnemyBaseLoginLevelModel = "enemy_base_login_levels"
var GameSessionModel = "game_sessions"
var HardwareModel = "hardwares"
var LevelBaseSessionModel = "level_base_sessions"
var LocationModel = "locations"
var ManuelFlowModel = "manuel_flows"
var OfferBehaviorModel = "offer_behaviors"
var ScreenClickModel = "screen_clicks"
var ScreenSwipeModel = "screen_swipes"
var InventoryModel = "inventorys"
var ItemModel = "items"
var SkillModel = "skills"
var TemporaryAbilityModel = "temporary_ability"
var ChurnPredictionSuccessRateModel = "churn_prediction_success_rates"
var AdvStrategyBehaviorModel = "adv_strategies"
