package cassandra

var AdvEventDataModel = "adv_events"
var BuyingEventModel = "buying_events"
var ChurnBlockerMlResultModel = "churn_bloker_ml_results"
var ChurnPredictionMlResultModel = "churn_prediction_ml_result_models"
var ClientDataModel = "client_data_models"
var EnemyBaseLevelFailModel = "enemy_base_level_fail_models"
var EnemyBaseLoginLevelModel = "enemy_base_login_level_models"
var GameSessionModel = "game_session_models"
var HardwareModel = "hardware_models"
var LevelBaseSessionModel = "level_base_session_models"
var LocationModel = "location_models"
var ManuelFlowModel = "manuel_flow_models"
var OfferBehaviorModel = "offer_behavior_models"
var ScreenClickModel = "screen_click_models"
var ScreenSwipeModel = "screen_swipe_models"
var InventoryModel = "inventory_models"
var ItemModel = "item_models"
var SkillModel = "skill_models"
var TemporaryAbilityModel = "temporary_ability_model"
